apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-dbs-platform-access
  namespace: investment-management
spec:
  provider: aws
  secretObjects:
    - secretName: secrets-prd-bcl-investment-porfolio-analysis-abaqus
      type: Opaque
      data:
        - objectName: rds-postgres-password
          key: postgres-password
  parameters:
    objects: |
      - objectName: "Password/prod/abaqus/investment-porfolio-analysis-db"
        objectType: secretsmanager
        jmesPath:
          - path: postgrespassword
            objectAlias: rds-postgres-password
