import { applicationPaths } from '../../../config/path';

const {
  accounts,
  home,
  pesosAccount,
  signing,
  dolarAccount,
  euroAccount,
  vistaAccount,
  vistaAccountExpenses,
  invoicesAccount,
  payments,
  transfers,
  financing,
  foreignTrade,
  investments,
  transfersHighAmounts,
  providerPayments,
  remunerationsPayments,
  h2hPayments,
  payrollPayments,
  servicesPayments,
  itayPayPlus,
  cashPooling,
  payrollSecureCheck,
  evaluationFinancing,
  warrantyCard,
  factoringFinancing,
  leasingFinancing,
  creditLineFinancing,
  creditCard,
  comexPortal,
  transferForeignCountry,
  currencyPurchaseSale,
  swiftMessages,
  timeDeposit,
  mutualFunds,
  actionsInvestments,
  summaryInvestments,
  collections,
  agreementPayment,
  multibankPAC,
  transbankSubscription,
} = applicationPaths;

const navigationItems = [
  {
    route: home,
    title: 'Inicio',
    icon: 'home',
    collapsed: true,
  },
  {
    route: signing,
    title: 'Firmas pendientes',
    notifications: 5,
    icon: 'signatures',
    collapsed: true,
  },
  {
    route: accounts,
    title: 'Cuentas',
    icon: 'account',
    collapsed: true,
    childrens: [
      {
        route: pesosAccount,
        title: 'Cuenta Pesos',
      },
      {
        route: dolarAccount,
        title: 'Cuenta Dólar',
      },
      {
        route: euroAccount,
        title: 'Cuenta Euro',
      },
      {
        route: vistaAccount,
        title: 'Cuenta Vista',
      },
      {
        route: vistaAccountExpenses,
        title: 'Cuenta Vista de gastos',
      },
      {
        route: invoicesAccount,
        title: 'Facturas',
      },
    ],
  },
  {
    route: payments,
    title: 'Pagos',
    icon: 'salary',
    collapsed: true,
    childrens: [
      { route: transfers, title: 'Transferencias' },
      { route: transfersHighAmounts, title: 'Transferencia Altos Montos' },
      { route: providerPayments, title: 'Pago Proveedores' },
      { route: remunerationsPayments, title: 'Pago de remuneraciones' },
      { route: h2hPayments, title: 'Pago H2H' },
      { route: payrollPayments, title: 'Nóminas en línea' },
      { route: servicesPayments, title: 'Pagos de servicios' },
      { route: itayPayPlus, title: 'Itaú PayPlus' },
      { route: cashPooling, title: 'Cash Pooling' },
      { route: payrollSecureCheck, title: 'Nómina Cheque Seguro' },
    ],
  },
  {
    route: financing,
    title: 'Financiamientos',
    icon: 'financing',
    collapsed: true,
    childrens: [
      { route: evaluationFinancing, title: 'Evaluación' },
      { route: warrantyCard, title: 'Boleta de garantía' },
      { route: factoringFinancing, title: 'Factoring' },
      { route: leasingFinancing, title: 'Leasing' },
      { route: creditLineFinancing, title: 'Línea de crédito' },
      { route: creditCard, title: 'Tarjeta de crédito' },
    ],
  },
  {
    route: foreignTrade,
    title: 'Comercio exterior',
    icon: 'outside',
    collapsed: true,
    childrens: [
      { route: comexPortal, title: 'Portal Comex' },
      { route: transferForeignCountry, title: 'Transferencia al extranjero' },
      { route: currencyPurchaseSale, title: 'Compra/venta de divisas' },
      { route: swiftMessages, title: 'Mensajes Swift históricos' },
    ],
  },
  {
    route: investments,
    title: 'Inversiones',
    icon: 'investments',
    collapsed: true,
    childrens: [
      { route: timeDeposit, title: 'Depósito a Plazo' },
      { route: mutualFunds, title: 'Fondos Mutuos' },
      { route: actionsInvestments, title: 'Acciones' },
      { route: summaryInvestments, title: 'Resumen de inversiones' },
    ],
  },
  {
    route: collections,
    title: 'Recaudación',
    icon: 'fundraising',
    collapsed: true,
    childrens: [
      { route: agreementPayment, title: 'Pago de convenio' },
      { route: multibankPAC, title: 'PAC multibanco' },
      { route: transbankSubscription, title: 'Abono Transbank' },
    ],
  },
];

export default navigationItems;
